const db = {
  "bautizo.jpg": {
    width: "136mm",
    height: "213mm",
    top: "0mm",
    left: "42mm",
    flip: false,
    inputs: [
      {
        top: "59mm",
        left: "65mm",
        width: "100mm",
        placeholder: "Nombre del bebé...",
        fontWeight: 700,
      },
      { top: "66.5mm", left: "62mm", width: "7mm", placeholder: "O/A" },
      { top: "66.5mm", left: "78mm", width: "87mm" },
      { top: "74mm", left: "65mm", width: "100mm" },
      {
        top: "82mm",
        left: "85mm",
        width: "80mm",
        placeholder: "Ciudad...",
      },
      {
        top: "89.5mm",
        left: "67mm",
        width: "12mm",
        textAlign: "center",
      },
      { top: "89.5mm", left: "103.5mm", width: "42mm" },
      {
        top: "89.5mm",
        left: "152mm",
        width: "11mm",
        textAlign: "center",
      },
      {
        top: "105.25mm",
        left: "67mm",
        width: "13mm",
        textAlign: "center",
      },
      { top: "105.25mm", left: "105mm", width: "36mm" },
      {
        top: "105.25mm",
        left: "149mm",
        width: "14mm",
        textAlign: "center",
      },
      { top: "125.5mm", left: "86mm", width: "80mm" },
      { top: "133mm", left: "112mm", width: "54mm" },
      { top: "141mm", left: "54mm", width: "23mm" },
      { top: "141mm", left: "84mm", width: "82mm" },
      {
        top: "148.5mm",
        left: "121mm",
        width: "42mm",
        textAlign: "center",
      },
      {
        top: "156.25mm",
        left: "75mm",
        width: "27mm",
        textAlign: "center",
      },
      {
        top: "156.25mm",
        left: "125mm",
        width: "38mm",
        textAlign: "center",
      },
      {
        top: "163mm",
        left: "50mm",
        width: "117mm",
        placeholder: "Notas marginales...",
        textAlign: "center",
        fontWeight: 700,
      },
      {
        top: "172mm",
        left: "84.5mm",
        width: "9mm",
        textAlign: "center",
      },
      { top: "172mm", left: "117mm", width: "24mm" },
      {
        top: "172mm",
        left: "147.5mm",
        width: "15mm",
        textAlign: "center",
      },
      {
        top: "198.75mm",
        left: "66mm",
        width: "84mm",
        placeholder: "RECTOR PBRO. Luis Armando González Torres",
        value: "RECTOR PBRO. Luis Armando González Torres",
        textAlign: "center",
      },
    ],
  },

  "comunion.jpg": {
    width: "208.96mm",
    height: "134.79mm",
    top: "0mm",
    left: "0mm",
    flip: true,
    inputs: [
      {
        top: "33.5mm",
        left: "52.5mm",
        width: "117mm",
        fontWeight: 700,
      },
      {
        top: "47.5mm",
        left: "49mm",
        width: "19mm",
        textAlign: "center",
      },
      { top: "47.5mm", left: "77.5mm", width: "62mm" },
      {
        top: "47.5mm",
        left: "146.5mm",
        width: "17mm",
        textAlign: "center",
      },
      { top: "55mm", left: "78.5mm", width: "113mm" },
      { top: "62mm", left: "43.5mm", width: "148mm" },
      { top: "69mm", left: "40.5mm", width: "151mm" },
      { top: "76mm", left: "40.5mm", width: "151mm" },
      { top: "83.5mm", left: "51mm", width: "140mm" },
      { top: "90.25mm", left: "41.5mm", width: "150mm" },
      { top: "96.75mm", left: "25mm", width: "166mm" },
      {
        top: "103.75mm",
        left: "32.5mm",
        width: "28mm",
        textAlign: "center",
      },
      {
        top: "110.5mm",
        left: "32.5mm",
        width: "28mm",
        textAlign: "center",
      },
      {
        top: "117.5mm",
        left: "32.5mm",
        width: "28mm",
        textAlign: "center",
      },
      {
        top: "113.5mm",
        left: "117mm",
        width: "78mm",
        placeholder: "RECTOR PBRO. LUIS ARMANDO GONZÁLEZ TORRES",
        value: "RECTOR PBRO. LUIS ARMANDO GONZÁLEZ TORRES",
      },
    ],
  },

  "matrimonio.jpg": {
    width: "227.92mm",
    height: "167.64mm",
    top: "0mm",
    left: "0mm",
    flip: true,
    inputs: [
      {
        top: "48.5mm",
        left: "34mm",
        width: "162mm",
        placeholder: "Nombre de los novios...",
        textAlign: "center",
        fontWeight: 700,
        fontSize: "16px",
      },
      {
        top: "78.5mm",
        left: "34mm",
        width: "10mm",
        textAlign: "center",
      },
      { top: "78.5mm", left: "52mm", width: "44mm" },
      {
        top: "78.5mm",
        left: "111.5mm",
        width: "7mm",
        textAlign: "center",
      },
      { top: "78.5mm", left: "155.5mm", width: "53mm" },
      { top: "98mm", left: "28.5mm", width: "83.5mm" },
      { top: "98mm", left: "120.5mm", width: "83.5mm" },
      { top: "110mm", left: "28.5mm", width: "83.5mm" },
      { top: "110mm", left: "120.5mm", width: "83.5mm" },
      { top: "116mm", left: "51mm", width: "45mm" },
      { top: "121mm", left: "51mm", width: "45mm" },
      { top: "126mm", left: "51mm", width: "45mm" },
      { top: "131mm", left: "75mm", width: "21mm" },
      { top: "136mm", left: "29mm", width: "67mm" },
      {
        top: "133.25mm",
        left: "120mm",
        width: "83mm",
        placeholder: "PBRO. LUIS ARMANDO GONZÁLEZ TORRES",
        value: "PBRO. LUIS ARMANDO GONZÁLEZ TORRES",
        textAlign: "center",
      },
    ],
  },

  "confirmacion.jpg": {
    width: "208.96mm",
    height: "134.79mm",
    top: "0mm",
    left: "0mm",
    flip: true,
    inputs: [
      {
        top: "33.5mm",
        left: "52.5mm",
        width: "117mm",
        fontWeight: 700,
      },
      {
        top: "47.5mm",
        left: "49mm",
        width: "19mm",
        textAlign: "center",
      },
      { top: "47.5mm", left: "77.5mm", width: "62mm" },
      {
        top: "47.5mm",
        left: "146.5mm",
        width: "17mm",
        textAlign: "center",
      },
      { top: "55mm", left: "78.5mm", width: "113mm" },
      { top: "62mm", left: "43.5mm", width: "148mm" },
      { top: "69mm", left: "40.5mm", width: "151mm" },
      { top: "76mm", left: "40.5mm", width: "151mm" },
      { top: "83.5mm", left: "51mm", width: "140mm" },
      { top: "90.25mm", left: "41.5mm", width: "150mm" },
      { top: "96.75mm", left: "25mm", width: "166mm" },
      {
        top: "103.75mm",
        left: "32.5mm",
        width: "28mm",
        textAlign: "center",
      },
      {
        top: "110.5mm",
        left: "32.5mm",
        width: "28mm",
        textAlign: "center",
      },
      {
        top: "117.5mm",
        left: "32.5mm",
        width: "28mm",
        textAlign: "center",
      },
      {
        top: "113.5mm",
        left: "117mm",
        width: "78mm",
        placeholder: "RECTOR PBRO. LUIS ARMANDO GONZÁLEZ TORRES",
        value: "RECTOR PBRO. LUIS ARMANDO GONZÁLEZ TORRES",
      },
    ],
  },
};

export { db };
